server:
  port: 9091
spring:
  application:
    name: user_service
  datasource:
    url: jdbc:mysql://134.209.106.84:3306/pc_api
    username: 'root'
    password: '@abc123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE