server:
  servlet:
    context-path: /
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: http://user-service:9091/
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: product_route
          uri: http://product-service:9090/
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: http://order-service:9092/
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
        - id: stockIO_route
          uri: http://stock-io-service:9093/
          predicates:
            - Path=/stockIO/**
          filters:
            - StripPrefix=1