server:
  servlet:
    context-path: /
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: http://localhost:9091/
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: product_route
          uri: http://localhost:9090/
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: http://localhost:9092/
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1